#!/bin/sh
case $1 in 
	"dbg")
		mkdir -p /tmp/cgnalec/
		cgnale -l ~/.local/share/cgnale/cgnale_libs/libcgnale_base.so -s "#include <cgnale.hpp>\n" -c $2.so.gen -s "{:cgnale.macros.get.create:}" > /tmp/cgnalec/$2.so.cpp
		g++ -g $3 -shared /tmp/cgnalec/$2.so.cpp -fPIC -I ~/.local/share/cgnale/include -o lib$2.so

	;;
	"clr")
		rm /tmp/cgnalec/$2.so.cpp
	;;
	*)
	cgnale -l ~/.local/share/cgnale/cgnale_libs/libcgnale_base.so -s "#include <cgnale.hpp>\n" -c $2.so.gen -s "{:cgnale.macros.get.create:}" | g++ $3 -shared -x c++ - -fPIC -I ~/.local/share/cgnale/include -o lib$2.so
	strip lib$2.so
	;;
esac
