#!/bin/sh
cgnale -l ~/.local/share/cgnale/cgnale_libs/libcgnale_base.so -s "#include <cgnale.hpp>\n" -c $1.so.gen -s "{:cgnale.macros.get.create:}" | g++ -x c++ -shared - -fPIC -I ~/.local/share/cgnale/include -o lib$1.so
strip lib$1.so
