#!/bin/sh

#This file is part of cgnale.

#    cgnale is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    cgnale is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with cgnale.  If not, see <http://www.gnu.org/licenses/>.

case $1 in 
	"dbg")
		mkdir -p /tmp/cgnalec/
		cgnale -l ~/.local/share/cgnale/cgnale_libs/libcgnalec.so -s "#include <cgnale.hpp>\n" -c $2.so.gen -s "{:cgnale.macros.get.create:}" > /tmp/cgnalec/$2.so.cpp
		g++ -g $3 -shared /tmp/cgnalec/$2.so.cpp -fPIC -I . -I ~/.local/share/cgnale/include -o lib$2.so

	;;
	"clr")
		rm /tmp/cgnalec/$2.so.cpp
	;;
	*)
	cgnale -l ~/.local/share/cgnale/cgnale_libs/libcgnalec.so -s "#include <cgnale.hpp>\n" -c $2.so.gen -s "{:cgnale.macros.get.create:}" | g++ $3 -shared -x c++ - -fPIC -I ~/.local/share/cgnale/include -o lib$2.so
	strip lib$2.so
	;;
esac
